apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: arkapps
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: HEAD
    helm:
      releaseName: grafana'
      valueFiles:
      - values.grafana.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
