apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: prometheus
spec:
  project: default
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: HEAD
    helm:
      releaseName: prometheus
      valueFiles:
      - values.prometheus.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus
